# Site settings
title: Tadaima
email: contact@d8vjork.es
description: Pure CSS Framework
twitter_username: d8vjork
github_username: d8vjork
authors: Social-chan Team and Tadaima contributors
current_version: 0.4.0

# Server
encoding: UTF-8
host: 0.0.0.0
port: 9001
baseurl: ""

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]